preferredBranch: develop
#exclude:
#- branch: do-nothing
#- branch: dont-touch-*
#- label: ignore-me
switchComment: >
  Hello @{{author}}. The base Branch of your pull Request has been changed to {{preferredBranch}}.
  Please use for all future contributions the {{preferredBranch}} Branch. Thank you!
