# Configuration for new-issue-welcome - https://github.com/behaviorbot/new-issue-welcome
# Comment to be posted to on first time issues
newIssueWelcomeComment: >
  Welcome and thank you for opening your first issue! If you have not done so already: Please make sure to follow the Issue Template

# Configuration for new-pr-welcome - https://github.com/behaviorbot/new-pr-welcome
# Comment to be posted to on PRs from first time contributors in your repository
newPRWelcomeComment: >
  Thank you for opening this pull request! If you have not done so already: Please check out our contributing rules here: [CONTRIBUTING.md](CONTRIBUTING.md)

# Configuration for first-pr-merge - https://github.com/behaviorbot/first-pr-merge
# Comment to be posted to on pull requests merged by a first time user
firstPRMergeComment: >
  Congrats on your first merged pull request! Thank you for your help to make this Project better byte by byte :) :+1: