# Configuration for close-issue-app - https://github.com/offu/close-issue-app

# Comment that will be sent if an issue is judged to be closed.
comment: "This issue is closed because it does not meet our issue template. Please copy the text from the [ISSUE_TEMPLATE.md](ISSUE_TEMPLATE.md) and fill out the requried informations. Thank you."
issueConfigs:
# There can be several configs for different kind of issues.
- content:
# Example 1: bug report
  - "Detailed Description"
  - "Steps to Reproduce"
  - "Expected Behavior"
  - "System Information"
- content:
# Example 2: feature request
  - "Use Case"
  - "Expected Behavior"
  - "Other Information"
# Optional configuration:
#
# whether the keywords are case-insensitive
# default value is false, which means keywords are case-sensitive
caseInsensitive: false
# the label that will be added when the bot close an issue
# The bot will only add a label if this property is set.
label: "closed by close-issue-app bot"
# The bot will ignore any issues that are opened or reopened by the user names in exception
exception:
  - "MeerMusik"
#  - "username2"
# The issue is judged to be legal if it includes all keywords from any of these two configs.
# Or it will be closed by the app.
