name: Bug Report
description: File a Bug Report
title: "[Type: Bug]: "
labels: [Type: Bug, Status: Triage]
assignees:
  - MeerMusik
body:
- type: markdown
  attributes:
  value: |
   Thanks for taking the time to fill out this Bug Report!
body:
- type: checkboxes
  attributes:
  label: Is there an existing issue for this?
  description: Please search to see if an issue already exists for the bug you encountered.
  options:
  - label: I have searched the existing issues
    required: true
  - type: textarea
    id: bug-description
    attributes:
      label: Describe the Bug ?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
      value: "A bug happened!"
    validations:
      required: true
  - type: dropdown
    id: operating_system
    attributes:
      label: What Operating System?
      multiple: true
      options:
        - BSD (supported by Ultimate++ but not tested)
        - Linux with KDE Version 5 (supported and tested)
        - Linux with GNOME Version 3 (supported but untested at the moment)
        - Linux other (support depends on used Distribution; usually not tested)
        - macOS (supported by Ultimate++ but not tested)
        - Windows 7
        - Windows 8.1
        - Windows 10
        - Other (not supported)
  validations:
    required: true
  - type: dropdown
    id: os_bitness
    attributes:
      label: Bitness Operating System
      description: What bitness is your Operating System?
      options:
        - X86_64 (64-Bit)
        - X86 (32-Bit)
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://example.com)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
