name: Bug Report
description: File a Bug Report
title: "[Bug]: "
labels: [New Bug]
assignees:
  - MeerMusik
body:
- type: markdown
  attributes:
    value: |
      Thanks for taking the time to fill out this Bug Report!
- type: checkboxes
  attributes:
    label: Is there an existing Issue for this Bug?
    description: Please search to see if an Issue already exists for the Bug you encountered.
    options:
    - label: I have searched the existing Issues
  validations:
    required: true
- type: textarea
  id: bug-description
  attributes:
    label: Describe the Bug ?
    description: Also tell us, what did you expect to happen?
    placeholder: Tell us what you see!
    value: "A bug happened!"
  validations:
    required: true
- type: dropdown
  id: os-name
  attributes:
    label: What Operating System?
    multiple: true
    options:
    - BSD (supported by Ultimate++ but not tested by me)
    - Linux with KDE Version 5 (supported and tested)
    - Linux with GNOME Version 3 (supported but untested at the moment by me)
    - Linux other (support depends on used Distribution; usually not tested by me)
    - macOS (supported by Ultimate++ but not tested by me)
    - Windows 7 (supported; tested in a VM)
    - Windows 8.1 (supported but not tested by me)
    - Windows 10 (supported and tested)
    - Other (not supported)
  validations:
    required: true
- type: dropdown
  id: os-bitness
  attributes:
    label: Architecture Operating System
    description: Which Architecture is your Operating System?
    multiple: true
    options:
    - X86 (32-Bit)
    - X86_64 (64-Bit)
  validations:
    required: true
- type: dropdown
  id: tool_bitness
  attributes:
    label: Architecture / Bitness of the Tool
    description: Which Architecture of the Tool do you use?
    multiple: true
    options:
    - X86 (32-Bit)
    - X86_64 (64-Bit)
  validations:
    required: true
- type: dropdown
  id: bug_appears_under_which_architecture
  attributes:
    label: Under which Architecture does the Bug happen?
    description: Does the Bug only happen under one or multiple Archtectures?
    options:
    - X86 (32-Bit)
    - X86_64 (64-Bit)
    - X86 AND X86_64
  validations:
    required: true
- type: textarea
  id: logs
  attributes:
    label: Relevant log output
    description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
    render: shell
- type: checkboxes
  id: code-of-conduct
  attributes:
    label: Code of Conduct
    description: By submitting this issue, you agree to follow our [Code of Conduct](CODE_OF_CONDUCT.md)
    options:
    - label: I agree to follow this project's Code of Conduct
      required: true
