name: Bug Report - Technical Problems only! - NOT FOR TRANSLATIONS! NOT FOR FEATURE REQUESTS!
description: Bugs. Glitches. UI Issues. If something does not work as expected or not at all. The App crashes or does not launch. - To request a Feature or Option, please use the "Feature Request" Form!
title: "[Bug]: "
labels: ['Type: Bug', 'Status: Not Confirmed']
assignees:
  - MeerMusik
body:
- type: markdown
  attributes:
    value: |
      Thank you filling out the Bug Report!
      If you wish to request a new Feature or Option, please use the Feature Request Form!
      For everything about missing or incomplete Translations, please use the Translation Form!
- type: checkboxes
  id: author-has-read-and-agrees-to-follow-contribution-rules
  attributes:
    label: Contribution Rules
    description: By submitting this issue, you A.) confirm that you have read the [Contributing Rules](CONTRIBUTING.md) and B.) agree to follow them as closely as possible
    options:
    - label: I confirm that I have read the Contribution Rules and agree to follow them as closely as possible
      required: true
- type: checkboxes
  id: code-of-conduct
  attributes:
    label: Code of Conduct
    description: By submitting this issue, you agree to follow the [Code of Conduct](CODE_OF_CONDUCT.md)
    options:
    - label: I agree to follow the Code of Conduct of this Project in addition to the Guidelines and Rules of GitHub
      required: true
- type: checkboxes
  attributes:
    label: Does an Issue already exist for this Bug?
    description: Please search through the Issues to see if an Issue already exists for the Bug you have encountered!
    options:
    - label: I have searched the existing Issues. There is no Issue for this specific Bug
      required: true
- type: textarea
  id: bug-description
  attributes:
    label: Describe the Bug
    description: Please describe the Bug as clear and concise as possible
    placeholder: Example - I opened an existing Document but the Editor is empty
    value: "Example: I opened an existing Document but the Editor is empty"
  validations:
    required: true
- type: dropdown
  id: os-name
  attributes:
    label: Which Operating System do you use? Multiple Answers possible
    multiple: true
    options:
    - Arch Linux with GNOME Version 3
    - Arch Linux with KDE Version 5
    - FreeBSD with GNOME 3
    - FreeBSD with KDE 5
    - Linux other
    - macOS 64-Bit
    - Manjaro Linux with GNOME Version 3
    - Manjaro Linux with KDE Version 5
    - Windows 7
    - Windows 8.1
    - Windows 10
    - Other (no direct support by me and / or the used Framework!)
  validations:
    required: true
- type: input
  id: name-bsd-linux-distribution-desktop-environment
  attributes:
    label: Name of the BSD or Linux Distribution and used Desktop Environment or the Name of the used OS if you selected "Other"
    description: "If you selected 'Other' above, type the Name of the OS and / or Desktop Environment."
  validations:
    required: false
- type: dropdown
  id: linux-wayland-x11
  attributes:
    label: Only when using Linux - Wayland or X11?
    description: Does the Bug happen under Wayland or X11? Or both? Multiple Answers possible
    multiple: true
    options:
    - Wayland only
    - X11 only
    - Wayland and X11
- type: dropdown
  id: os-bitness
  attributes:
    label: Architecture Operating System
    description: Which Architecture is your Operating System? Multiple Answers possible
    multiple: true
    options:
    - X86 (32-Bit)
    - X86_64 (64-Bit)
    - 64-Bit with 32-Bit Multilibs, Compatibility Layer or something similar
  validations:
    required: true
- type: dropdown
  id: tool_bitness
  attributes:
    label: Architecture of the Tool
    description: Which Architecture of the Tool do you use? Multiple Answers possible
    multiple: true
    options:
    - X86 (32-Bit)
    - X86_64 (64-Bit)
  validations:
    required: true
- type: dropdown
  id: severity-of-the-bug
  attributes:
    label: Does the Tool crash to Desktop or become unresponsive?
    description: When you experience the Bug, does the Tool crash or is it still usable? Does it become unresponsive?
    multiple: false
    options:
    - The Tool always crashes to Desktop (CTD)
    - The Tool sometimes crashes to Desktop (CTD)
    - The Tool does NOT crash to Desktop and is still usable
    - The Tool does NOT crash to Desktop but becomes unresponsive and must be terminated through the Task Manager
    - Answer does not apply - The Tool does not launch (FIXME - IFELSE NEED GH API)
  validations:
    required: true
- type: textarea
  id: additional_infos_from_issue_creator
  attributes:
    label: Anything you would like to add?
    description: If you have additional Infos you would like to add, you can do this here
- type: textarea
  id: additional_logs
  attributes:
    label: Relevant Log Output
    description: Please copy and paste any relevant Log Output if available. This will be automatically formatted into code, so no need for backticks.
    render: shell
