# Do not allow creating Issues without a body text
blank_issues_enabled: false
# Some Links that should help getting in Contact, answering Questions etc. to hopefully limit unnecessary Issues
contact_links:
  - name: FAQ - English - Answers get added as needed
    url: https://github.com/MeerMusik/issue-template-test/blob/main/Docs/FAQ_English.md
    about: Should answer the most asked Questions. If you have still Questions after reading the FAQ, feel free to create a new Issue by using the Question Form.
  - name: FAQ - German - Answers get added as needed
    url: https://github.com/MeerMusik/issue-template-test/blob/main/Docs/FAQ_German.md
    about: Should answer the most asked Questions. If you have still Questions after reading the FAQ, feel free to create a new Issue by using the Question Form.
  - name: PLACEHOLDER - Manual - Coming later
    url: https://www..com
    about: The Manual will be added around or shortly after Version 1.0 has been published
  - name: Twitter
    url: https://twitter.com/MeerMusik
    about: Ask me a short Question on Twitter. Replies take somewhere between 2 - 96 hours. Tweets are public and readable by everyone! If you need to send personal Data, send me a Direct Message = DM!
