name: Feature Request - For technical Problems, use the Bug Report Form! For everything about Translations, use the Translation Form!
description: To wish a new Feature or a new Option (or multiple Options) for an existing Feature. To request multiple new Features, please create a new Issue for each new Feature! Thank you!
title: "[Feature Request]: "
labels: ['Type: Feature Request']
assignees:
  - MeerMusik
body:
- type: markdown
  attributes:
    value: |
      Thank you for taking the time to fill out the Feature Request Form!
      If you wish to request multiple new Features, please create a new Issue for each new Feature!
      For technical Problems, please use the Bug Report Form. For everything about Translations, please use the Translation Form.
- type: checkboxes
  attributes:
    label: Does an Issue already exist for this Feature Request?
    description: Please search through the Issues to see if an Issue already exists for the Feature you wish to request!
    options:
    - label: I have searched the existing Issues. There is no Issue for this specific Feature or Option
      required: true
- type: textarea
  id: new-feature-description
  attributes:
    label: Describe the Feature
    description: Please describe the Feature or Option as clear and concise as possible
    placeholder: Example - When I open the Print Preview, I need to change the Fontsize.
    value: "Example - When I open the Print Preview, I need to change the Fontsize."
  validations:
    required: true
- type: textarea
  id: new-feature-usecase
  attributes:
    label: Describe the Usecase
    description: Please describe the Usecase as clear and concise as possible
    placeholder: Example - The Text in the Print Preview is too small and I can not read it
    value: "Example - The Text in the Print Preview is too small and I can not read it."
  validations:
    required: true
- type: checkboxes
  id: code-of-conduct
  attributes:
    label: Code of Conduct
    description: By submitting this issue, you agree to follow our [Code of Conduct](CODE_OF_CONDUCT.md)
    options:
    - label: I agree to follow the Code of Conduct of this Project in addition to the Guidelines and Rules of GitHub
      required: true
