name: Question - Please read the FAQ and the Manual first, which are listed below on this Page! If you still have Questions after reading both, feel free to ask them by using this Form.
description: As long as your Questions have to do with the Content in this Repository, they are considered on Topic.
title: "[Question]: "
labels: ['Type: Question']
assignees:
  - MeerMusik
body:
- type: markdown
  attributes:
    value: |
      Keep in mind, that this Issue will be public and can be read by anyone! Do not publish private Informations like your eMail Address here!
- type: checkboxes
  id: author-has-read-and-agrees-to-follow-contribution-rules
  attributes:
    label: Contribution Rules
    description: By submitting this issue, you A.) confirm that you have read the [Contribution Rules](CONTRIBUTING.md) and B.) agree to follow them as closely as possible
    options:
    - label: I confirm that I have read the Contribution Rules and agree to follow them as closely as possible
      required: true
- type: checkboxes
  id: author-has-read-and-agrees-to-follow-code-of-conduct
  attributes:
    label: Code of Conduct
    description: By submitting this issue, you A.) confirm that you have read the [Code of Conduct](CODE_OF_CONDUCT.md) and B.) agree to follow it
    options:
    - label: I confirm that I have read the Code of Conduct and agree to follow it
      required: true
- type: checkboxes
  attributes:
    label: Does an open Issue already exist for this Question?
    description: Please search through the Issues to see if there is already an open Issue for your Question!
    options:
    - label: I have searched the existing Issues. There is no Issue for this specific Question
      required: true
- type: textarea
  id: new-question
  attributes:
    label: Ask away!
    description: Ask whatever you want, as long as it has to do with the Content of this Repository!
    placeholder: Ask whatever you want, as long as it has to do with the Content of this Repository!
    value: "Ask whatever you want, as long as it has to do with the Content of this Repository!"
  validations:
    required: true
